### ISSUE TITLE
Support all resources

### ISSUE THREAD

**Issue by moltar** [awslabs/diagram-as-code#103]
**Is your feature request related to a problem? Please describe.**

I am running `awsdac` against a template, and many basic resources are not supported.

```
WARN[0000] Unknown type: AWS::IAM::User
WARN[0000] Unknown type: AWS::IAM::Policy
WARN[0000] Unknown type: AWS::IAM::AccessKey
WARN[0000] Unknown type: AWS::SecretsManager::Secret
WARN[0000] Unknown type: AWS::S3::Bucket
```

**Describe the solution you'd like**

Support most common resources.

**Describe alternatives you've considered**

Other tools.

**Additional context**

N/A

**Comment by a2ush** [comment]
Thank you for creating the issue and providing CloudFormation resource types you need to be supported. I appreciate your feedback.

I have implemented the following resource types you listed:
```
Resources:
  IAMAccessKey:
    Type: AWS::IAM::AccessKey
  IAMUser:
    Type: AWS::IAM::User
  Secrets:
    Type: AWS::SecretsManager::Secret
  IAMPolicy:
    Type: AWS::IAM::Policy
  S3:
    Type: AWS::S3::Bucket
```
![output](https://github.com/awslabs/diagram-as-code/assets/41433979/64ef74ce-8d9c-4f85-9817-de65b39591aa)

However, for `AWS::IAM::User` resource type, there is currently no specific icon available[1], so I'm using a generic "User" icon.
If you're not satisfied with the default icon, you can generate a `dac file` from the CloudFormation template and set a preset to change the icon.
Here are the steps:

1. Run the command with the `--dac-file` option
```
$ awsdac --cfn-template cfn-test.yaml --dac-file 
[Completed] dac (diagram-as-code) data written to output.yaml
[Completed] AWS infrastructure diagram generated: output.png
```
2. Edit the generated dac file `output.yaml`
```diff
        IAMUser:
            Type: AWS::IAM::User
+          Preset: "Users"
```
※ You can find the available preset values in the definition file[2]

3. Run the command with the edited dac file
```
$ awsdac output.yaml                             
[Completed] AWS infrastructure diagram generated: output.png
```
![image](https://github.com/awslabs/diagram-as-code/assets/41433979/c0d73b40-b4c6-458e-b737-8f05a330f424)

[1] https://aws.amazon.com/architecture/icons/?nc1=h_ls
[2] https://github.com/awslabs/diagram-as-code/blob/main/definitions/definition-for-aws-icons-light.yaml#L7517-L7524

### Note
I have created a separate issue https://github.com/awslabs/diagram-as-code/issues/104 to address the handling of resource types without icons. Please wait for the resolution of that issue. 
※ For resource types without a specific icon, you can still use any of the provided icons by specifying a preset in the dac file as the above process.
