### ISSUE TITLE
Connection lines

### ISSUE THREAD

**Issue by pchaganti** [awslabs/diagram-as-code#11]
Any plans to add connection lines between resources?

thanks!

**Comment by ugwis** [comment]
Yes, Currently supports a straight line between resources. The start and end points of the line specify the location as the 16-wind rose of the resource (e.g. NNW). https://github.com/awslabs/diagram-as-code/blob/main/doc/links.md

The documentation is not comprehensive enough, and I will work on adding more details later.

Additionally, I would like to implement features such as curves, dotted, arrows, and orthogonal lines, but I haven't implemented them yet.

**Comment by pchaganti** [comment]
Awesome! thank you!
