### ISSUE TITLE
Allow Custom Definition YAML

### ISSUE THREAD

**Issue by austinsonger** [awslabs/diagram-as-code#137]
**Is your feature request related to a problem? Please describe.**
Custom Definition YAML

**Additional context**

It's difficult to use this for FedRAMP when I need to show all other non-aws services.

**Comment by a2ush** [comment]
Thank you for creating the issue!

Currently, we provide the method that you can use custom definition files as the following;
https://github.com/awslabs/diagram-as-code/blob/main/doc/introduction.md#definitionfiles-section
 > If you want to customize the resource definitions locally, you can specify a local file path instead:
```
    DefinitionFiles:
      - Type: LocalFile
        LocalFile: "<your definition file path (e.g. ~/Desktop/your-custom-definition.yaml)>"
```

Could you please confirm if this is the way to achieve your requirement?
