### ISSUE TITLE
Documentation for orthogonal links

### ISSUE THREAD

**Issue by mikicz** [awslabs/diagram-as-code#143]
Orthogonal links are very useful, but are not mention in docs - only when I started looking through existing tickets / PRs to see if you can add labels on links, I found https://github.com/awslabs/diagram-as-code/pull/134 which adds the support. This is however not mentioned in the docs at all (https://github.com/awslabs/diagram-as-code/blob/main/doc/links.md)

**Comment by ugwis** [comment]
Thank you for creating the issue!
Added doc for orthogonal link.
https://github.com/awslabs/diagram-as-code/blob/main/doc/links.md#orthogonal
