### ISSUE TITLE
[REQ] Arrow heads for connection lines

### ISSUE THREAD

**Issue by pchaganti** [awslabs/diagram-as-code#26]
The standard followed in diagrams published by AWS over the years, shows the connection lines with arrowheads. Is this something that will be potentially supported in the future? The arrowheads really add context and meaning to the diagrams by indicating the direction of the flow.

thanks!

**Comment by ugwis** [comment]
Thank you for your feedback!
Yes! I'm working now so please wait for a while.

**Comment by ugwis** [comment]
We have added #27 following two arrow types, three widths, and custom length options. [Doc](https://github.com/ugwis/diagram-as-code/blob/main/doc/links.md#arrow-head) and [example](https://github.com/ugwis/diagram-as-code/tree/main/examples#load-balancing-web-servers-using-alb) should help. We believe these additions will meet most of your requirements, but if you have any other requests, please feel free to create an issue and let us know!

![arrows](https://github.com/awslabs/diagram-as-code/assets/914815/57e917cf-b087-4723-9ea4-aa16805331ac)

**Comment by pchaganti** [comment]
Thank you! This looks awesome!
