### ISSUE TITLE
Title string overflows image when Title is long

### ISSUE THREAD

**Issue by a2ush** [awslabs/diagram-as-code#67]
## Issue
![title-miss](https://github.com/awslabs/diagram-as-code/assets/41433979/d419a105-fa02-4278-818d-062741341fb1)

## Expected
 * The title string should be fully contained within the image boundaries.
 * The title should wrap to a new line if it exceeds the image width to prevent horizontal overflow.

**Comment by ugwis** [comment]
Merged PR for expanding the group to fit the resource.
